// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAnnounceConfig = "announce_configs"

// AnnounceConfig mapped from table <announce_configs>
type AnnounceConfig struct {
	ID     int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Status string `gorm:"column:status;type:varchar(255);not null;comment:状态名称" json:"status"` // 状态名称
	Body   string `gorm:"column:body;type:text;not null;comment:状态内容" json:"body"`             // 状态内容
}

// TableName AnnounceConfig's table name
func (*AnnounceConfig) TableName() string {
	return TableNameAnnounceConfig
}
