// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameApplicantTime = "applicant_times"

// ApplicantTime mapped from table <applicant_times>
type ApplicantTime struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`
	ApplicantID int64          `gorm:"column:applicant_id;not null;comment:申请ID" json:"applicant_id"`
	Group_      string         `gorm:"column:group;not null;comment:申请组别" json:"group"`
	TimeID      int64          `gorm:"column:time_id;not null;comment:时间ID" json:"time_id"`
	RoomID      int64          `gorm:"column:room_id;not null;comment:房间ID" json:"room_id"`
	Extend      string         `gorm:"column:extend;comment:扩展信息" json:"extend"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`
}

// TableName ApplicantTime's table name
func (*ApplicantTime) TableName() string {
	return TableNameApplicantTime
}
