// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameApplicantTime = "applicant_times"

// ApplicantTime mapped from table <applicant_times>
type ApplicantTime struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ApplicantID int64          `gorm:"column:applicant_id;not null;comment:申请ID" json:"applicant_id"` // 申请ID
	Group_      string         `gorm:"column:group;not null;comment:申请组别" json:"group"`               // 申请组别
	TimeID      int64          `gorm:"column:time_id;not null;comment:时间ID" json:"time_id"`           // 时间ID
	RoomID      int64          `gorm:"column:room_id;not null;comment:房间ID" json:"room_id"`           // 房间ID
	Extend      string         `gorm:"column:extend;comment:扩展信息" json:"extend"`                      // 扩展信息
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ApplicantTime's table name
func (*ApplicantTime) TableName() string {
	return TableNameApplicantTime
}
