// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameConfiguration = "configuration"

// Configuration mapped from table <configuration>
type Configuration struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Key       string         `gorm:"column:key;not null;comment:键" json:"key"`     // 键
	Value     string         `gorm:"column:value;not null;comment:值" json:"value"` // 值
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Configuration's table name
func (*Configuration) TableName() string {
	return TableNameConfiguration
}
