// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMigration = "migrations"

// Migration mapped from table <migrations>
type Migration struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`
	Migration string `gorm:"column:migration;not null" json:"migration"`
	Batch     int32  `gorm:"column:batch;not null" json:"batch"`
}

// TableName Migration's table name
func (*Migration) TableName() string {
	return TableNameMigration
}
