// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameQuestion = "questions"

// Question mapped from table <questions>
type Question struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Question  string         `gorm:"column:question;type:text;not null;comment:问题内容" json:"question"`    // 问题内容
	Group_    string         `gorm:"column:group;type:varchar(32);not null;comment:问题所属组别" json:"group"` // 问题所属组别
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
