// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameReceiveSm = "receive_sms"

// ReceiveSm mapped from table <receive_sms>
type ReceiveSm struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Phone     string         `gorm:"column:phone;not null;comment:手机号码" json:"phone"`   // 手机号码
	Content   string         `gorm:"column:content;not null;comment:内容" json:"content"` // 内容
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ReceiveSm's table name
func (*ReceiveSm) TableName() string {
	return TableNameReceiveSm
}
