// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoom = "rooms"

// Room mapped from table <rooms>
type Room struct {
	ID                 int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`
	Name               string         `gorm:"column:name;not null;comment:房间名称" json:"name"`
	Location           string         `gorm:"column:location;not null;comment:房间位置" json:"location"`
	Status             int32          `gorm:"column:status;not null;comment:状态 0-已停用 1-休息中 2-等待中 3-已占用" json:"status"`
	StatusUpdatedAt    time.Time      `gorm:"column:status_updated_at;not null;default:CURRENT_TIMESTAMP;comment:状态更新时间" json:"status_updated_at"`
	ApplicantTimeID    int64          `gorm:"column:applicant_time_id;not null;comment:申请时间ID" json:"applicant_time_id"`
	InterviewerComment string         `gorm:"column:interviewer_comment;comment:面试官留言" json:"interviewer_comment"`
	ReceiverComment    string         `gorm:"column:receiver_comment;comment:接待者留言" json:"receiver_comment"`
	GroupLabel         string         `gorm:"column:group_label;not null;comment:组别标签" json:"group_label"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`
	CreatedAt          time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`
	UpdatedBy          int64          `gorm:"column:updated_by;not null;comment:更新者" json:"updated_by"`
}

// TableName Room's table name
func (*Room) TableName() string {
	return TableNameRoom
}
