// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTime = "times"

// Time mapped from table <times>
type Time struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Group_    string         `gorm:"column:group;type:varchar(32);not null;comment:组别" json:"group"`           // 组别
	Time      time.Time      `gorm:"column:time;type:datetime(3);not null;comment:时间" json:"time"`             // 时间
	Rank      int32          `gorm:"column:rank;type:int;not null;comment:顺序" json:"rank"`                     // 顺序
	Location  string         `gorm:"column:location;type:varchar(32);comment:地点" json:"location"`              // 地点
	TotalCnt  int32          `gorm:"column:total_cnt;type:int;not null;default:1;comment:总数" json:"total_cnt"` // 总数
	Campus    string         `gorm:"column:campus;type:varchar(32);comment:校区" json:"campus"`                  // 校区
	Grade     string         `gorm:"column:grade;type:varchar(32);comment:年级" json:"grade"`                    // 年级
	MeetingID string         `gorm:"column:meeting_id;type:varchar(32);comment:会议ID" json:"meeting_id"`        // 会议ID
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName Time's table name
func (*Time) TableName() string {
	return TableNameTime
}
