// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTime = "times"

// Time mapped from table <times>
type Time struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Group_    string         `gorm:"column:group;not null;comment:组别" json:"group"`                   // 组别
	Time      time.Time      `gorm:"column:time;not null;comment:时间" json:"time"`                     // 时间
	Rank      int32          `gorm:"column:rank;not null;comment:顺序" json:"rank"`                     // 顺序
	Location  string         `gorm:"column:location;comment:地点" json:"location"`                      // 地点
	TotalCnt  int32          `gorm:"column:total_cnt;not null;default:1;comment:总数" json:"total_cnt"` // 总数
	Campus    string         `gorm:"column:campus;comment:校区" json:"campus"`                          // 校区
	Grade     string         `gorm:"column:grade;comment:年级" json:"grade"`                            // 年级
	MeetingID string         `gorm:"column:meeting_id;comment:会议ID" json:"meeting_id"`                // 会议ID
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Time's table name
func (*Time) TableName() string {
	return TableNameTime
}
