// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTimeConfig = "time_configs"

// TimeConfig mapped from table <time_configs>
type TimeConfig struct {
	Key   string    `gorm:"column:key;primaryKey;comment:键" json:"key"`   // 键
	Value time.Time `gorm:"column:value;not null;comment:值" json:"value"` // 值
}

// TableName TimeConfig's table name
func (*TimeConfig) TableName() string {
	return TableNameTimeConfig
}
