# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Hr Backend Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hr-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Current version
        id: get-current-tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./hr-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: scutrobot/hr-service:${{steps.get-current-tag.outputs.tag }},scutrobot/hr-service:latest

  hr-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Current version
        id: get-current-tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./hr-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: scutrobot/hr-api:${{steps.get-current-tag.outputs.tag }},scutrobot/hr-api:latest

  hr-admin-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Current version
        id: get-current-tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./hr-admin-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: scutrobot/hr-admin-service:${{steps.get-current-tag.outputs.tag }},scutrobot/hr-admin-service:latest

  hr-admin-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Current version
        id: get-current-tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./hr-admin-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: scutrobot/hr-admin-api:${{steps.get-current-tag.outputs.tag }},scutrobot/hr-admin-api:latest
